require("rafaelNMeyer.config.remap")
require("rafaelNMeyer.config.set")
require("rafaelNMeyer.config.lazy")
require("rafaelNMeyer.config.colorscheme")
require("rafaelNMeyer.config.floating_terminal")
